# Generated by Django 6.0.5 on 2026-06-01 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('hot', 'Жара'), ('warm', 'Тепло'), ('cool', 'Прохлада'), ('cold', 'Холод'), ('rain', 'Дождь'), ('snow', 'Снег'), ('any', 'Любая')], default='any', max_length=10, verbose_name='Условие')),
                ('temp_min', models.FloatField(default=-50, verbose_name='Температура от, °C')),
                ('temp_max', models.FloatField(default=50, verbose_name='Температура до, °C')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_rules', to='catalog.family', verbose_name='Семейство')),
            ],
            options={
                'verbose_name': 'Правило погоды',
                'verbose_name_plural': 'Правила погоды',
                'ordering': ['condition', 'temp_min'],
            },
        ),
    ]
