# Generated by Django 6.0.5 on 2026-06-01 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Семейство',
                'verbose_name_plural': 'Семейства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='catalog.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('type', models.CharField(choices=[('top', 'Верхняя'), ('heart', 'Сердечная'), ('base', 'Базовая')], default='heart', max_length=10, verbose_name='Тип')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Нота',
                'verbose_name_plural': 'Ноты',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='note_unique_name_type')],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Гендер')),
                ('longevity', models.CharField(choices=[('weak', 'Слабая'), ('medium', 'Средняя'), ('strong', 'Сильная')], default='medium', max_length=10, verbose_name='Стойкость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfumes', to='catalog.brand', verbose_name='Бренд')),
                ('families', models.ManyToManyField(blank=True, related_name='perfumes', to='catalog.family', verbose_name='Семейства')),
                ('notes', models.ManyToManyField(blank=True, related_name='perfumes', to='catalog.note', verbose_name='Ноты')),
            ],
            options={
                'verbose_name': 'Парфюм',
                'verbose_name_plural': 'Парфюмы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='catalog.perfume', verbose_name='Парфюм')),
            ],
            options={
                'verbose_name': 'Запись коллекции',
                'verbose_name_plural': 'Коллекция',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='brand_unique_per_country'),
        ),
        migrations.AddConstraint(
            model_name='perfume',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='perfume_unique_name_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'perfume'), name='collection_unique_user_perfume'),
        ),
    ]
